# Generated by Django 5.2.5 on 2025-08-28 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonForSpecialConsideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Reason for special consideration',
                'verbose_name_plural': 'Reasons for special consideration',
            },
        ),
        migrations.CreateModel(
            name='SocialDomesticEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Social-domestic environment',
                'verbose_name_plural': 'Social-domestic environments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='utils.neighborhood', verbose_name='neighborhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Inspector',
                'verbose_name_plural': 'Inspectors',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('pinfl', models.CharField(max_length=14, verbose_name='pinfl')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('last_psychiatric_appointment_date', models.DateField(blank=True, null=True, verbose_name='date of the last psychiatric appointment')),
                ('last_home_visit_by_doctor_date', models.DateField(blank=True, null=True, verbose_name='date of last home visit by a doctor or nurse')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='if the patient has not been seen by a doctor within a month, the reason')),
                ('receiving_supportive_therapy', models.CharField(blank=True, choices=[('regularly_receiving', 'Regularly receiving'), ('not_receiving', 'Not receiving'), ('quickly_receiving', 'Quickly receiving'), ('reraly_receiving', 'Reraly receiving')], max_length=30, null=True, verbose_name='receiving supportive therapy')),
                ('description_for_special_consideration', models.CharField(blank=True, max_length=500, null=True, verbose_name='description for special consideration')),
                ('alcohol_and_drug_use', models.CharField(blank=True, choices=[('regularly_receiving', 'Regularly receiving'), ('not_receiving', 'Not receiving'), ('quickly_receiving', 'Quickly receiving'), ('reraly_receiving', 'Reraly receiving')], max_length=30, null=True, verbose_name='alcohol and drug use')),
                ('where_is_now', models.CharField(blank=True, choices=[('at_home', 'At home'), ('in_hospital', 'In hospital'), ('out_of_the_area', 'Out of the area'), ('address_unknown', 'Address unknown')], max_length=30, null=True, verbose_name='where is now')),
                ('description_where_is_now', models.CharField(blank=True, max_length=500, null=True, verbose_name='description where is now')),
                ('last_hospitalization_from', models.DateField(blank=True, null=True, verbose_name='from date of last hospitalization')),
                ('last_hospitalization_to', models.DateField(blank=True, null=True, verbose_name='to date of last hospitalization')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='psytracks.doctor', verbose_name='doctor')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='utils.inspector', verbose_name='inspector')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='utils.neighborhood', verbose_name='neighborhood')),
                ('reason_for_special_consideration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='psytracks.reasonforspecialconsideration', verbose_name='reason for special consideration')),
                ('social_domestic_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='psytracks.socialdomesticenvironment', verbose_name='social-domestic environment')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
