# Generated by Django 5.2.5 on 2025-08-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasonforspecialconsideration',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='socialdomesticenvironment',
            name='name_ru',
        ),
    ]
