# Generated by Django 5.2.5 on 2025-08-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0002_remove_reasonforspecialconsideration_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasonforspecialconsideration',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='socialdomesticenvironment',
            name='name_uz',
        ),
    ]
