# Generated by Django 5.2.5 on 2025-08-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0003_remove_reasonforspecialconsideration_name_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='alcohol_and_drug_use',
            field=models.CharField(blank=True, choices=[('alcohol_and_drug', 'Alcohol and drug'), ('alcohol', 'Alcohol'), ('drug', 'Drug'), ('not_consume', 'Not consume')], max_length=30, null=True, verbose_name='alcohol and drug use'),
        ),
    ]
