# Generated by Django 5.2.5 on 2025-08-31 13:05

import psytracks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0004_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_home_visit_by_doctor_file',
            field=models.FileField(blank=True, null=True, upload_to=psytracks.models.upload_to_home_visit_by_doctor, validators=[psytracks.models.validate_file_size, psytracks.models.validate_file_extension], verbose_name='file of last home visit by a doctor or nurse'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_hospitalization_from_file',
            field=models.FileField(blank=True, null=True, upload_to=psytracks.models.upload_to_last_hospitalization_from, validators=[psytracks.models.validate_file_size, psytracks.models.validate_file_extension], verbose_name='from date of last hospitalization'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_hospitalization_to_file',
            field=models.FileField(blank=True, null=True, upload_to=psytracks.models.upload_to_last_hospitalization_to, validators=[psytracks.models.validate_file_size, psytracks.models.validate_file_extension], verbose_name='to date of last hospitalization'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_psychiatric_appointment_file',
            field=models.FileField(blank=True, null=True, upload_to=psytracks.models.upload_to_psychiatric_appointment_file, validators=[psytracks.models.validate_file_size, psytracks.models.validate_file_extension], verbose_name='file of the last psychiatric appointment'),
        ),
    ]
