# Generated by Django 5.2.5 on 2025-09-01 14:01

import django.db.models.deletion
import psytracks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0005_patient_last_home_visit_by_doctor_file_and_more'),
        ('utils', '0004_settingskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='utils.neighborhood', verbose_name='neighborhood'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_hospitalization_from_file',
            field=models.FileField(blank=True, null=True, upload_to=psytracks.models.upload_to_last_hospitalization_from, validators=[psytracks.models.validate_file_size, psytracks.models.validate_file_extension], verbose_name='from date of last hospitalization file'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_hospitalization_to_file',
            field=models.FileField(blank=True, null=True, upload_to=psytracks.models.upload_to_last_hospitalization_to, validators=[psytracks.models.validate_file_size, psytracks.models.validate_file_extension], verbose_name='to date of last hospitalization file'),
        ),
    ]
