# Generated by Django 5.2.5 on 2025-09-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0006_doctor_phone_alter_doctor_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
