# Generated by Django 5.2.5 on 2025-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0007_remove_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_aggressive',
            field=models.BooleanField(default=False, verbose_name='is aggressive'),
        ),
    ]
