# Generated by Django 5.2.5 on 2025-09-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0008_patient_is_aggressive'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='max_examination_interval',
            field=models.IntegerField(default=30, verbose_name='maximal examination interval (in days)'),
        ),
    ]
