# Generated by Django 5.2.5 on 2025-09-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0009_patient_max_examination_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='brigade_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='brigade_number'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='polyclinic_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='polyclinic name'),
        ),
    ]
