# Generated by Django 5.2.5 on 2025-09-10 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0010_doctor_birth_date_doctor_brigade_number_and_more'),
        ('utils', '0006_inspector_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.CreateModel(
            name='Psychiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychiatrists', to='utils.district', verbose_name='district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychiatrist', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Psychiatrist',
                'verbose_name_plural': 'Psychiatrists',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='psychiatrist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='psytracks.psychiatrist', verbose_name='psychiatrist'),
        ),
    ]
