# Generated by Django 5.2.5 on 2025-09-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytracks', '0013_alter_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_abroad_long_term',
            field=models.BooleanField(default=False, verbose_name='is abroad long term'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_convicted',
            field=models.BooleanField(default=False, verbose_name='is convicted'),
        ),
    ]
