# Generated by Django 5.2.5 on 2025-09-06 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_telegram_id'),
        ('utils', '0006_inspector_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='utils.district', verbose_name='district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='district', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'District admin',
                'verbose_name_plural': 'District admins',
            },
        ),
        migrations.CreateModel(
            name='RegionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='utils.region', verbose_name='region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Region admin',
                'verbose_name_plural': 'Region admins',
            },
        ),
    ]
