# Generated by Django 5.2.5 on 2025-09-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_districtadmin_regionadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionadmin',
            old_name='district',
            new_name='region',
        ),
    ]
