# Generated by Django 5.2.5 on 2025-08-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_ru',
        ),
    ]
