# Generated by Django 5.2.5 on 2025-08-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_remove_district_name_ru_remove_neighborhood_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_uz',
        ),
    ]
