# Generated by Django 5.2.5 on 2025-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_remove_district_name_uz_remove_neighborhood_name_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Settings key',
                'verbose_name_plural': 'Settings keys',
            },
        ),
    ]
