# Generated by Django 5.2.5 on 2025-09-04 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_settingskey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictMonitoring',
            fields=[
            ],
            options={
                'verbose_name': 'Monitoring',
                'verbose_name_plural': 'Monitoring',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('utils.district',),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
