# Generated by Django 5.2.5 on 2025-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_districtmonitoring_neighborhood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='phone'),
        ),
    ]
